"""add indexes

Revision ID: 8a9b0c1d2e3f
Revises: 7f6d157a5e07
Create Date: 2026-02-19 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9b0c1d2e3f'
down_revision: Union[str, None] = '7f6d157a5e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_user_audit_logs_performed_by'), 'user_audit_logs', ['performed_by'], unique=False)
    op.create_index(op.f('ix_dataset_audit_logs_performed_by'), 'dataset_audit_logs', ['performed_by'], unique=False)
    op.create_index(op.f('ix_ticket_attachments_uploaded_by'), 'ticket_attachments', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_attachments_uploaded_by'), table_name='ticket_attachments')
    op.drop_index(op.f('ix_dataset_audit_logs_performed_by'), table_name='dataset_audit_logs')
    op.drop_index(op.f('ix_user_audit_logs_performed_by'), table_name='user_audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    # ### end Alembic commands ###
